name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo apt-get -y update
        sudo apt-get -y install cmake clang
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_TESTING=FALSE -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - name: build
      run: cmake --build build
